# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 16:23
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.encrypted


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPets', models.PositiveIntegerField(default=1)),
                ('goal', models.PositiveIntegerField(default=100)),
                ('progress', models.IntegerField(default=0)),
                ('checkNum', django_extensions.db.fields.encrypted.EncryptedCharField(default='1234', max_length=None)),
                ('saveNum', django_extensions.db.fields.encrypted.EncryptedCharField(default='1234', max_length=None)),
                ('numTrans', models.PositiveIntegerField(default=0)),
                ('lastPay', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(default='123 Test', max_length=100)),
                ('city', models.CharField(default='Princeton', max_length=100)),
                ('state', models.CharField(default='NJ', max_length=100)),
                ('postalcode', models.CharField(default='08544', max_length=5)),
                ('dob', models.CharField(default='1995-01-01', max_length=10)),
                ('ssn', django_extensions.db.fields.encrypted.EncryptedCharField(default='1234', max_length=15)),
                ('phone', models.CharField(default='1234567890', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='pet',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Pet'),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
