# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPets', models.PositiveIntegerField()),
                ('goal', models.PositiveIntegerField()),
                ('progress', models.IntegerField()),
                ('baseCost', models.IntegerField()),
                ('numTrans', models.PositiveIntegerField()),
                ('lastPay', models.DateField()),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Pet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='auto_now_add=True')),
                ('amount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner')),
            ],
        ),
    ]
