# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_owner_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='baseCost',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
