# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pet_basecost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='baseCost',
        ),
    ]
