# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160406_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
