# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160406_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='baseCost',
        ),
        migrations.AddField(
            model_name='owner',
            name='checkNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='saveNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='owner',
            name='goal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='lastPay',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='numPets',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='owner',
            name='numTrans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='owner',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
