# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 04:40
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160413_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='pet',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Pet'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
