# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160413_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='lastPay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
