# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 17:54
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160413_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='pet',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Pet'),
        ),
    ]
